# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['seal_python']

package_data = \
{'': ['*']}

install_requires = \
['certifi', 'dnspython', 'pycryptodome', 'typing-extensions']

setup_kwargs = {
    'name': 'seal_python',
    'version': '0.0.1',
    'description': 'A Python implementation of the SEAL specification which aims to allow users to assign attribution to media',
    'long_description': '# SEAL-Python\n[Secure Evidence Attribution Label (SEAL)](https://github.com/hackerfactor/SEAL) allows users to assign attribution with authentication to media.\n\nThis is an (incomplete) implementation of SEAL in Python according to [Version 1.1.4](https://github.com/hackerfactor/SEAL/blob/d05d7b6e81a025cd1b00919549e1a013115ec134/SPECIFICATION.md).\n\n---\n\n***Important Note:** The implementation currently only works for signing and verifying <u>PNG</u> files*',
    'author': 'Oliver Smith',
    # 'author_email': 'None',
    'maintainer': 'None',
    # 'maintainer_email': 'None',
    'url': 'https://github.com/OliverSm1th/SEAL-Python',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.9',
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
